# Generated by Django 3.0.8 on 2020-08-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vid', models.UUIDField(db_index=True)),
                ('stage1', models.IntegerField()),
                ('stage2', models.IntegerField()),
                ('stage3', models.IntegerField()),
                ('stage4', models.IntegerField()),
                ('stage5', models.IntegerField()),
                ('stage6', models.IntegerField()),
                ('stage7', models.IntegerField()),
                ('stage8', models.IntegerField()),
                ('stage_long', models.IntegerField()),
                ('forget_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vid', models.UUIDField(db_index=True)),
                ('circle_stage', models.IntegerField()),
                ('last_op_time', models.IntegerField()),
                ('word_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=256)),
                ('language', models.CharField(db_index=True, max_length=2)),
                ('meaning', models.TextField()),
            ],
        ),
    ]
